<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="V-DEV03" name="marketTypesTest.LMM.Loan_ND_NewMode_Inputs" tests="5" failures="0" timestamp="1 Jul 2022 03:19:29 GMT" time="0.000" errors="5">
  <testcase name="infoPage_NewMode_Inputs" time="0.000" classname="marketTypesTest.LMM.Loan_ND_NewMode_Inputs">
    <error type="java.lang.Throwable" message="Method Loan_ND_NewMode_Inputs.infoPage_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Loan_ND_NewMode_Inputs.infoPage_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- infoPage_NewMode_Inputs -->
  <testcase name="dealSave_Using_NewMode_Inputs" time="0.000" classname="marketTypesTest.LMM.Loan_ND_NewMode_Inputs">
    <error type="java.lang.Throwable" message="Method Loan_ND_NewMode_Inputs.dealSave_Using_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Loan_ND_NewMode_Inputs.dealSave_Using_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- dealSave_Using_NewMode_Inputs -->
  <testcase name="bankDetails_NewMode_Inputs" time="0.000" classname="marketTypesTest.LMM.Loan_ND_NewMode_Inputs">
    <error type="java.lang.Throwable" message="Method Loan_ND_NewMode_Inputs.bankDetails_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Loan_ND_NewMode_Inputs.bankDetails_NewMode_Inputs()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- bankDetails_NewMode_Inputs -->
  <testcase name="frontPage_NewMode_Inputs" time="0.000" classname="marketTypesTest.LMM.Loan_ND_NewMode_Inputs">
    <error type="java.lang.IllegalArgumentException" message="Cannot find elements when the XPath is null.">
      <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
	at org.openqa.selenium.internal.Require$ArgumentChecker.nonNull(Require.java:204)
	at org.openqa.selenium.By$ByXPath.<init>(By.java:287)
	at org.openqa.selenium.By.xpath(By.java:89)
	at frameWorks.pageObjectModel.CommonElements.Page_Load_BackDrop_EL(CommonElements.java:137)
	at handleFields.PageLoad_CircleBar_Handle.is_PageLoaded_Check(PageLoad_CircleBar_Handle.java:21)
	at handleFields.AlertMsg.alert_MsgHandle(AlertMsg.java:20)
	at beforeTest.Login.login(Login.java:78)
	at beforeTest.Bfr_Any_Test.bfr_Any_Test(Bfr_Any_Test.java:37)
	at marketTypesTest.LMM.Loan_ND_NewMode_Inputs.beforeTestConfigs(Loan_ND_NewMode_Inputs.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- frontPage_NewMode_Inputs -->
  <testcase name="cashFlow_NewMode" time="0.000" classname="marketTypesTest.LMM.Loan_ND_NewMode_Inputs">
    <error type="java.lang.Throwable" message="Method Loan_ND_NewMode_Inputs.cashFlow_NewMode()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Loan_ND_NewMode_Inputs.cashFlow_NewMode()[pri:0, instance:marketTypesTest.LMM.Loan_ND_NewMode_Inputs@3c09711b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- cashFlow_NewMode -->
</testsuite> <!-- marketTypesTest.LMM.Loan_ND_NewMode_Inputs -->
